In [11]:
import os
import pathlib

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import tensorflow as tf
import librosa.display
import librosa

from tensorflow.keras import layers
from tensorflow.keras import models
from IPython import display

# Set the seed value for experiment reproducibility.
seed = 42
tf.random.set_seed(seed)
np.random.seed(seed)

# load more files with librosa
pathAudio = "C:/Users/treib/Documents/HDM/2. Semester/Technology Lab/Musik/Test/"
files = librosa.util.find_files(pathAudio, ext=['wav'])
files = np.asarray(files)
A = []
#T = tf.zeros([, 2], tf.float64)

for y in files:
    test_file = tf.io.read_file(y)
    test_audio, _ = tf.audio.decode_wav(contents=test_file)
#    tf.add(T, test_audio)
    print(test_audio)


tf.Tensor(
[[ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 ...
 [-0.22317505 -0.3404541 ]
 [-0.22131348 -0.33898926]
 [-0.21966553 -0.33773804]], shape=(132300, 2), dtype=float32)
tf.Tensor(
[[-0.20465088 -0.32348633]
 [-0.1972351  -0.3138733 ]
 [-0.22433472 -0.33926392]
 ...
 [-0.46957397 -0.2638855 ]
 [-0.46704102 -0.25750732]
 [-0.4685974  -0.25598145]], shape=(132300, 2), dtype=float32)
tf.Tensor(
[[ 0.00015259  0.01202393]
 [-0.0007019   0.01379395]
 [-0.00158691  0.01553345]
 ...
 [ 0.02993774  0.05319214]
 [ 0.03118896  0.05493164]
 [ 0.03213501  0.05639648]], shape=(40263, 2), dtype=float32)
tf.Tensor(
[[-0.21850586 -0.33706665]
 [-0.21783447 -0.33706665]
 [-0.21746826 -0.33770752]
 ...
 [-0.1739502  -0.05383301]
 [-0.17324829 -0.06109619]
 [-0.16763306 -0.05645752]], shape=(132300, 2), dtype=float32)
tf.Tensor(
[[-0.15945435 -0.05184937]
 [-0.15768433 -0.05096436]
 [-0.16415405 -0.0512085 ]
 ...
 [-0.00692749  0.02780151]
 [-0.00619507  0.0269

In [ ]:
import librosa
import pandas as pd
import numpy as np


y,sr = librosa.load('C:/Users/treib/Documents/HDM/2. Semester/Technology Lab/Musik/Test/Tea K Pea - nauticals_1.wav')

df = pd.DataFrame(y, columns=['Amplitude'])

df.index = [(1/sr)*i for i in range(len(df.index))]

y = np.mean(y)



df[0:1]


#https://stackoverflow.com/questions/62261039/how-can-i-get-a-dataframe-of-frequency-and-time-from-a-wav-file-in-python